library(reticulate)
library(jsonlite)
library(tidyverse)
library(randomForest)
library(xgboost)
library(data.table)
library(arrow)
library(duckdb)
library(stringr)
library(lubridate)
library(ggplot2)
library(generalCorr)

cpih <- fread("CPIH Annual Rate 00.csv")
ppi <- fread("Producer Price Inflation.csv")
