library(reticulate)
library(jsonlite)
library(tidyverse)
library(randomForest)
library(xgboost)
library(data.table)
library(arrow)
library(duckdb)
library(stringr)
library(lubridate)
library(ggplot2)
library(generalCorr)
library(onsr)
library(ggfortify)

cpih <- ons_get("cpih01")
inf_exp <- fread("inflation_expectations.csv")
